services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

    command: npm run dev

    ports:
      - "5173:5173"

    stdin_open: true
    tty: true


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend:/backend

    command: go run main.go

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true