services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

    command: npm run dev

    ports:
      - "5173:5173"

    stdin_open: true
    tty: true